export const ADD_CATEGORY = "ADD_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const EDIT_CATEGORY = "EDIT_CATEGORY"

export const ADD_EXPENSE = "ADD_EXPENSE"
export const DELETE_EXPENSE = "DELETE_EXPENSE"
export const EDIT_EXPENSE = "EDIT_EXPENSE"
export const FILTER_EXPENSE = "FILTER_EXPENSE"
